---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_users_custom:
  clickuser:
    password: clickuser
    networks:
      - 192.168.88.205
