---
  - name: clickhouse-role
    src: git@github.com:juls-blekh/clickhouse-role.git
    scm: git
    version: "0.1.0"
  - name: vector-role
    src: git@github.com:juls-blekh/vector-role.git
    scm: git
    version: "0.1.0"
  - name: lighthouse-role
    src: git@github.com:juls-blekh/lighthouse-role.git
    scm: git
    version: "0.1.0"
