---
# Path to vector configs
vector_config_dir: "{{ ansible_user_dir }}/vector_config"
vector_config:
  sources:
    sample_file:
      type: file
      read_from: beginning
      ignore_older_secs: 600
      include:
        - /home/blekh/logs/*.log
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        -  sample-file
      endpoint: http://192.168.88.205:8123
      databases: logs
      auth:
        password: clickuser
        user: clickuser
      skip_unknown_fields: true
      compression: gzip